"""N1 equivalent of the committed n8n string-input business operation.

Python MCP SDK 2.1.1 / Pydantic 2.13.5. Schema is generated by the SDK.
The n8n wording is deliberately retained as model-visible comparison data.
"""
import importlib.metadata
import json
import os
from pathlib import Path

from mcp.server.mcpserver import MCPServer
from starlette.responses import JSONResponse

server = MCPServer("inference-lens-n1-string-input")
output = Path(os.environ["INFERENCE_LENS_N1_OUTPUT"])


@server.tool(
    description="Echo one string through a deterministic n8n sub-workflow for the Inference Lens provider-wire contract fixture.",
    structured_output=False,
)
async def il_echo_string(text: str) -> str:
    result = json.dumps([{
        "fixture": "IL_N0_STRING_INPUT", "echoed": text, "receivedType": "string"
    }], separators=(",", ":"), ensure_ascii=False)
    # Exclusive creation proves this bounded capture executed the tool once.
    with (output / "python-execution.json").open("x") as evidence:
        json.dump({"arguments": {"text": text}, "result": result}, evidence, indent=2)
    return result


@server.custom_route("/health", methods=["GET"])
async def health(request):
    return JSONResponse({"ready": True})


if __name__ == "__main__":
    versions = {name: importlib.metadata.version(name) for name in ["mcp", "pydantic"]}
    if versions != {"mcp": "2.1.1", "pydantic": "2.13.5"}:
        raise RuntimeError(f"N1 fixture requires pinned SDK versions; got {versions}")
    (output / "python-versions.json").write_text(json.dumps(versions, indent=2))
    server.run(transport="streamable-http", host="127.0.0.1", port=44021,
               streamable_http_path="/mcp", stateless_http=True, json_response=True)
